-- liquibase formatted sql

-- changeset anton:1
CREATE TABLE faculty
(
    faculty_id BIGINT NOT NULL generated by default as identity,
    name_faculty VARCHAR(255) NOT NULL ,
    color VARCHAR(255) NOT NULL,
    primary key (faculty_id)
)

-- changeset anton:1.1
ALTER  TABLE  hogwarts.public.faculty
    ADD  CONSTRAINT  constr_faculty  UNIQUE (name_faculty);